import 'dart:typed_data' show Uint8List;

import 'package:cloud_firestore/cloud_firestore.dart';

Future<List> getSantri() async {
  List<String> santri = List();
  await Firestore.instance.collection("santri").getDocuments().then((value) =>
    {
  for (int i = 0; i < value.documents.length; i++) {
      santri.add(value.documents[i]['nama'])
}
    }
  );
  return santri;
}
const allsurat = [
  "Al-Baqarah",
  "Ali 'Imran",
  "An-Nisaa'",
  "Al-Maa`idah",
  "Al-An'am",
  "Al-A'raaf",
  "Al-Anfaal",
  "At-Taubah",
  "Yunus",
  "Huud",
  "Yusuf",
  "Ar-Ra'd",
  "Ibrahim",
  "Al-Hijr",
  "An-Nahl",
  "Al-Israa'",
  "Al-Kahfi",
  "Maryam",
  "Thaahaa",
  "Al-Anbiyaa'",
  "Al-Hajj",
  "Al-Mu'minuun",
  "An-Nuur",
  "Al-Furqaan",
  "Asy-Syu'araa'",
  "An-Naml",
  "Al-Qashash",
  "Al-'Ankabuut",
  "Ar-Ruum",
  "Luqman",
  "As-Sajdah",
  "Al-Ahzab",
  "Saba'",
  "Faathir",
  "Yaasiin",
  "Ash-Shaaffat",
  "Shaad",
  "Az-Zumar",
  "Al-Mu'min",
  "Fushshilat",
  "Asy-Syuura",
  "Az-Zukhruf",
  "Ad-Dukhaan",
  "Al-Jaatsiyah",
  "Al-Ahqaaf",
  "Muhammad",
  "Al-Fath",
  "Al-Hujuraat",
  "Qaaf",
  "Adz-Dzariyaat",
  "Ath-Thuur",
  "An-Najm",
  "Al-Qamar",
  "Ar-Rahmaan",
  "Al-Waaqi'ah",
  "Al-Hadiid",
  "Al-Mujaadilah",
  "Al-Hasyr",
  "Al-Mumtahanah",
  "Ash-Shaff",
  "Al-Jumu'ah",
  "Al-Munaafiquun",
  "At-Taghaabun",
  "Ath-Thalaaq",
  "At-Tahriim",
  "Al-Mulk",
  "Al-Qalam",
  "Al-Haaqqah",
  "Al-Ma'aarij",
  "Nuh",
  "Al-Jin",
  "Al-Muzzammil",
  "Al-Muddatstsir",
  "Al-Qiyaamah",
  "Al-Insaan",
  "Al-Mursalaat",
  "An-Naba'",
  "An-Nazi'at",
  "'Abasa",
  "At-Takwiir",
  "Al-Infithaar",
  "Al-Muthaffifiin",
  "Al-Insyiqaaq",
  "Al-Buruuj",
  "Ath-Thaariq",
  "Al-A'laa",
  "Al-Ghaasyiyah",
  "Al-Fajr",
  "Al-Balad",
  "Asy-Syams",
  "Al-Lail",
  "Adh-Dhuhaa",
  "Alam Nasyrah",
  "At-Tiin",
  "Al-'Alaq",
  "Al-Qadr",
  "Al-Bayyinah",
  "Al-Zalzalah",
  "Al-'Aadiyaat",
  "Al-Qaari'ah",
  "At-Takaatsur",
  "Al-'Ashr",
  "Al-Humazah",
  "Al-Fiil",
  "Quraisy",
  "Al-Maa'uun",
  "Al-Kautsar",
  "Al-Kaafiruun",
  "An-Nashr",
  "Al-Lahab",
  "Al-Ikhlash",
  "Al-Falaq",
  "An-Naas",
];
getDataSantri() async{
  List<String> santri = await getSantri();
  print(santri.length);
  return santri.length;
}
